In [1]:
import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# code van Wail - moet aangepast worden 

# for column_name in ['P1_Longitude', 'P1_Latitude']:
#     df = df[df[column_name].notna()]
#     df[column_name] = df[column_name].str.replace('.', '')
#     df[column_name] = df[column_name].str.replace('⁰', '.')
#     df[column_name] = df[column_name].str.replace('˚', '.')
#     df[column_name] = df[column_name].apply(lambda x: x[:-1])
#     df[column_name] = df[column_name].str.replace("'", '')



# writer = pd.ExcelWriter('data/locations/FarmerLocationExtract4Interns_sentinel-hub.xlsx', engine='xlsxwriter')
# df.to_excel(writer, sheet_name='Sheet1')
# writer.save()

In [3]:
# convert coordinations_file (csv file) into a dataframe
coordinations_df = pd.read_excel('data/locations/FarmerLocationExtract4Interns.xlsx')

In [4]:
coordinations_df

,Name,Mobile (anonymized),Mouza,GP,Block,Land_ID1,Land_Size2,P1_Latitude,P1_Longitude
0,TEMP_NAME,PHONE01,Baksa,11 No Arrah,Nayagram,40,0.167,"21˚54'39.876""","87˚1'18.996"""
1,TEMP_NAME,PHONE02,Banskhali,11 No Arrah,Nayagram,100/53,0.333,"21˚53'55.50432""","87˚4'54.97068"""
2,TEMP_NAME,PHONE03,Pathrasol,12 No Chandrarekha,Nayagram,51,0.333,"21˚58'11.97383""","87˚1'57.48758"""
3,TEMP_NAME,PHONE04,Ramkrishnapur,11 No Arrah,Nayagram,36/947,0.167,"21˚53'57.47928""","87˚1'39.47664"""
4,TEMP_NAME,PHONE05,Bamdiha,11 No Arrah,Nayagram,92,0.333,"21˚55'26.2056""","87˚2'29.9184"""
...,...,...,...,...,...,...,...,...,...
245,TEMP_NAME,PHONE246,Bamdiha,11 No Arrah,Nayagram,230,0.260,21⁰55'47.784'',87⁰2'16.5912''
246,TEMP_NAME,PHONE247,Bamdiha,11 No Arrah,Nayagram,47/1,0.260,21⁰55'47.5356'',87⁰2'16.5912''
247,TEMP_NAME,PHONE248,Bamdiha,11 No Arrah,Nayagram,285,0.520,21⁰52'13.3968'',87⁰5'30.772''
248,TEMP_NAME,PHONE249,Bamdiha,11 No Arrah,Nayagram,51,0.520,21⁰55'48.7128'',87⁰2'15.8064''
249,TEMP_NAME,PHONE250,Bamdiha,11 No Arrah,Nayagram,42,0.100,21⁰93'15.3264'',87⁰03'43.2479''

In [5]:
geolocations  = coordinations_df[['P1_Longitude', 'P1_Latitude']].copy()

In [6]:
geolocations

        P1_Longitude      P1_Latitude
0       87˚1'18.996"    21˚54'39.876"
1     87˚4'54.97068"  21˚53'55.50432"
2     87˚1'57.48758"  21˚58'11.97383"
3     87˚1'39.47664"  21˚53'57.47928"
4      87˚2'29.9184"   21˚55'26.2056"
..               ...              ...
245   87⁰2'16.5912''   21⁰55'47.784''
246   87⁰2'16.5912''  21⁰55'47.5356''
247    87⁰5'30.772''  21⁰52'13.3968''
248   87⁰2'15.8064''  21⁰55'48.7128''
249  87⁰03'43.2479''  21⁰93'15.3264''

[250 rows x 2 columns]

In [7]:
import re

In [8]:
def dms2dd(degrees, minutes, seconds):
    dd = float(degrees) + float(minutes)/60 + float(seconds)/(60*60);
#     if direction == 'E' or direction == 'N':
#         dd *= -1
    return dd;

def parse_dms(dms):
    parts = re.split('[˚\'"]+', dms)
    #print(parts)
    lat = dms2dd(parts[0], parts[1], parts[2])

    return (lat)

def parse_dms2(dms):
    parts = re.split('[⁰\'"]+', dms)
    #print(parts)
    lat = dms2dd(parts[0], parts[1], parts[2])

    return (lat)

In [9]:
# foute data, cleaning
geolocations = geolocations.drop([27])
geolocations = geolocations.drop([40])
geolocations = geolocations.drop([69])
geolocations = geolocations.drop([84])
geolocations = geolocations.drop([98])
geolocations = geolocations.drop([141])
geolocations = geolocations.drop([152])
geolocations = geolocations.drop([173])
geolocations = geolocations.drop([233])

In [10]:
teller = 0
LongitudeS = []
LatitudeS = []
for i in range(len(geolocations['P1_Longitude'])):
    teller += 1
    if '⁰' in geolocations['P1_Longitude'].iloc[i]:
        long = parse_dms2(geolocations['P1_Longitude'].iloc[i])
        lat = parse_dms2(geolocations['P1_Latitude'].iloc[i])
        LongitudeS.append(long)
        LatitudeS.append(lat)
        print(teller)
        print(long, lat)
    else:
        long = parse_dms(geolocations['P1_Longitude'].iloc[i])
        lat = parse_dms(geolocations['P1_Latitude'].iloc[i])
        LongitudeS.append(long)
        LatitudeS.append(lat)
        print(teller)
        print(long, lat)

1
87.02194333333333 21.911076666666666
2
87.0819363 21.8987512
3
87.03263543888889 21.969992730555553
4
87.0276324 21.899299799999998
5
87.041644 21.923946
6
87.025687 21.901816
7
87.041619 21.923952
8
87.02194333333333 21.911076666666666
9
87.0444698 21.892153
10
87.048682 21.898691
11
87.044234 21.902925999999997
12
87.044578 21.902811
13
87.032093 21.883627
14
87.04650699999999 21.902025
15
87.04522899999999 21.902656
16
87.04302294444444 21.902452999999998
17
87.04298266666666 21.909152
18
87.040058 21.900012999999998
19
87.040038 21.899612
20
87.05136 21.90909
21
87.054532 21.908459999999998
22
87.053394 21.911934
23
87.060929 21.907042999999998
24
87.05287299999999 21.912891
25
87.05287299999999 21.913052999999998
26
87.053642 21.907919
27
87.05373399999999 21.908171
28
87.047657 21.901045
29
87.065393 21.897063
30
87.05513499999999 21.893435
31
87.055888 21.894578
32
87.059113 21.894241
33
87.07838199999999 21.884581999999998
34
87.02084166666667 21.913853333333332
35
87.02298527777778 21.907791666666665
36
87.0075986 21.923480700000002
37
87.01902 21.912513333333333
38
87.00754166666667 21.921940000000003
39
87.00768 21.921736666666668
40
87.069255 21.897083
41
87.0587105 21.8949697
42
87.066908 21.897199999999998
43
87.0615217 21.8947833
44
87.064537 21.895882999999998
45
87.060707 21.894842
46
87.0625869 21.8952179
47
87.06104599999999 21.895488
48
87.02212816666666 21.91078
49
87.01476833333334 21.919968333333333
50
87.017925 21.91437333333333
51
87.025135 21.906921999999998
52
87.01425333333333 21.91939166666667
53
87.013685 21.919801666666668
54
87.02236 21.910626666666666
55
87.02197666666666 21.910735
56
87.02599333333333 21.90636333333333
57
87.02321166666667 21.913073333333333
58
87.02245166666667 21.91038
59
87.02321166666667 21.913073333333333
60
87.02141833333333 21.913095
61
87.03274836944445 21.968948230555554
62
87.03310706944444 21.968535680555554
63
87.0348996 21.970244899999997
64
87.02887311944444 21.973982219444444
65
87.02864238888888 21.97371297222222
66
87.01488666666667 21.969631666666665
67
87.02321166666667 21.913073333333333
68
87.01455166666666 21.919341666666668
69
87.02218666666667 21.91068333333333
70
87.0813364 21.930126561111113
71
87.03371771944444 21.969758838888886
72
87.02827508055556 21.967943309583333
73
87.02865933888889 21.96678706111111
74
87.0288257888889 21.96736116111111
75
87.02838493888889 21.966639
76
87.03340211944445 21.96849336944444
77
87.03323781944444 21.968441230555555
78
87.03334535 21.96809156111111
79
87.03085241111111 21.96839381111111
80
87.03317352777778 21.967779480555553
81
87.0280370611111 21.971421830555553
82
87.03294643888889 21.968189924999997
83
87.03366831111111 21.967958319444442
84
87.03323438055556 21.967963688888887
85
87.03081066944445 21.965903649999998
86
87.0814922 21.929785980555558
87
87.0807239611111 21.92871581111111
88
87.08084816944444 21.929480180555558
89
87.08094833055556 21.929626969444445
90
87.037461 21.930757
91
87.037611 21.930705
92
87.04011 21.92794
93
88.51305555555555 24.81277777777778
94
87.038561 21.928302000000002
95
87.036922 21.932229
96
87.03692699999999 21.932362
97
87.038136 21.932113
98
87.037962 21.931350000000002
99
87.038219 21.931432
100
87.039252 21.932025
101
87.03912199999999 21.932066000000003
102
87.039148 21.931898
103
87.051536 21.909284
104
89.43944444444445 21.906217555555553
105
87.054726 21.909367
106
87.05081799999999 21.90916
107
87.054677 21.909157999999998
108
87.06780409999999 21.884916
109
87.022555 21.895005
110
87.027489 21.899251
111
87.027764 21.899224
112
87.024899 21.899698
113
87.028204 21.902735999999997
114
87.01695194444444 21.898709
115
83.028631 21.903885
116
87.077112 21.884878999999998
117
87.078428 21.884821
118
87.030016 21.900112999999997
119
87.07685099999999 21.885219
120
87.080495 21.887415999999998
121
87.079628 21.887602
122
87.079314 21.88786
123
87.07789199999999 21.927253
124
87.079438 21.927030000000002
125
87.07950699999999 21.927417000000002
126
87.07956999999999 21.927796
127
87.077236 21.927755
128
87.079439 21.928017
129
87.07788599999999 21.928282000000003
130
87.079098 21.926746
131
87.0691174 21.919656369444446
132
87.06891768888889 21.91925425
133
87.0699629111111 21.919365480555555
134
87.05178099999999 21.912039999999998
135
87.051554 21.912307
136
87.052122 21.906859444444443
137
87.05203999999999 21.906883999999998
138
87.05172499999999 21.912187
139
87.051672 21.91225
140
87.05342499999999 21.907069999999997
141
87.09160999999999 21.881052
142
87.037961 21.896916
143
87.015466 21.897738999999998
144
195.11 21.898515
145
87.078334 21.885044
146
87.077255 21.883406
147
87.049779 21.89483
148
87.062316 21.893431
149
87.05957699999999 21.894719
150
87.032674 21.941022
151
87.03738 21.931199
152
87.037391 21.931367
153
87.03715199999999 21.931396
154
87.036964 21.931525
155
87.032914 21.93372
156
87.038122 21.932715
157
87.032613 21.933694
158
87.032557 21.933351000000002
159
87.032676 21.933026
160
87.03707899999999 163.19
161
87.037216 21.931019000000003
162
87.037336 21.931538
163
87.038444 21.932722000000002
164
87.038191 21.932593
165
87.038286 21.932541
166
87.038343 21.932719000000002
167
87.033637 21.933091
168
87.033716 21.932978000000002
169
87.03299 21.933611
170
87.02121833333334 21.910871666666665
171
87.02099 21.911465
172
87.02097833333333 21.911661666666664
173
87.02104 21.91184833333333
174
87.02070666666667 21.911855
175
87.02032666666666 21.912066666666664
176
87.02032666666666 21.91249333333333
177
87.019755 21.913251666666664
178
87.01992333333334 21.913596666666667
179
87.01883166666667 21.914005
180
87.01889 21.914088333333332
181
87.02130666666666 21.910406666666667
182
87.02165166666667 21.91023333333333
183
87.02121833333334 21.90993333333333
184
87.039061 21.92775
185
87.039508 21.927726
186
87.03944299999999 21.927785
187
87.038659 21.038659000000003
188
87.03910499999999 21.929281
189
87.03970699999999 21.929152000000002
190
87.038912 21.927799
191
87.038591 21.928858
192
87.038488 21.929299
193
87.03860999999999 21.929125000000003
194
87.048842 21.90412
195
87.055677 21.91229
196
87.060709 21.906937
197
87.055905 21.912177999999997
198
87.049238 21.902386999999997
199
87.055773 21.912269
200
87.049114 21.902396999999997
201
87.04918388888889 21.902379
202
87.049076 21.91079
203
87.04912 21.910760999999997
204
87.049767 21.911628
205
87.049154 21.90487
206
87.04853 21.901403
207
87.04853 21.898903
208
87.04853 21.898903
209
87.06372499999999 21.92125
210
87.06288033333333 21.920352
211
87.064122 21.92106
212
87.06419888888888 21.92254
213
87.09285899999999 21.866928
214
87.09285899999999 21.866928
215
87.084745 21.88726
216
87.08575499999999 21.878765
217
87.029563 21.901068
218
87.02974999999999 21.900772
219
87.029737 21.900931
220
87.02936 21.901068
221
87.02929999999999 21.901014
222
87.03013388888888 21.900771
223
87.085044 21.877905000000002
224
87.085562 21.878777
225
87.085664 21.878815
226
87.094419 21.873284
227
87.091782 21.870381000000002
228
87.095355 21.871067
229
87.059812 21.894866
230
87.06231616666666 21.89342988888889
231
87.06231347222221 21.876764333333334
232
87.037174 21.930869
233
87.038174 21.930396000000002
234
87.03798 21.930296972222223
235
87.038044 21.930166
236
87.03829999999999 21.930102
237
87.037942 21.929940000000002
238
87.037942 21.929871000000002
239
87.0918811111111 21.870388000000002
240
87.037724 21.930198
241
87.06201330555555 22.554257333333332

In [11]:
data = {'Longitude':  LongitudeS,
        'Latitude': LatitudeS
        }
Converted = pd.DataFrame (data, columns = ['Longitude','Latitude'])
Converted

     Longitude   Latitude
0    87.021943  21.911077
1    87.081936  21.898751
2    87.032635  21.969993
3    87.027632  21.899300
4    87.041644  21.923946
..         ...        ...
236  87.037942  21.929940
237  87.037942  21.929871
238  87.091881  21.870388
239  87.037724  21.930198
240  87.062013  22.554257

[241 rows x 2 columns]

In [12]:
Converted.to_csv(r'C:\Users\Game PC\Desktop\skfb\BB8\data\locations\Converted.csv', index = False)

## Convert geolocations into bounding boxes